name: Test

on: [push]

jobs:
  test:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Install uv
      uses: astral-sh/setup-uv@v5
      
    - name: Set up Python
      run: uv python install

    - name: Install the project
      run: uv sync --all-extras --dev

    - name: Check for correct formatting, static typing, linting, etc...
      run: |
        make check-format

    # - name: Test with pytest
    #   # env: {}
    #   run: |
    #     make test

    # - name: "Upload coverage to Codecov"
    #   uses: codecov/codecov-action@v3
    #   with:
    #     # codecov sometimes return error without reason
    #     fail_ci_if_error: false
